from typing import Literal, overload

class HeaderTuple:
    def __init__(self, name: str | bytes, value: str | bytes) -> None: ...
    def __getitem__(self, index: object): ...
    def __contains__(self, item: object) -> bool: ...

class Encoder:
    def __init__(self) -> None: ...
    @property
    def header_table_size(self) -> int: ...
    @header_table_size.setter
    def header_table_size(self, value: int) -> None: ...
    def encode(self, headers: object, huffman: bool = ...):  # -> bytes:
        ...

class Decoder:
    def __init__(self, max_header_list_size: int = ...) -> None: ...
    @property
    def header_table_size(self) -> int:
        """
        Controls the size of the HPACK header table.
        """
        ...

    @header_table_size.setter
    def header_table_size(self, value: int) -> None: ...
    @overload
    def decode(self, data: object) -> list[tuple[str, str]]: ...
    @overload
    def decode(
        self, data: object, raw: Literal[True] = ...
    ) -> list[tuple[bytes, bytes]]: ...
    @overload
    def decode(
        self, data: object, raw: Literal[False] = ...
    ) -> list[tuple[str, str]]: ...
    def decode(
        self, data: object, raw: bool = ...
    ) -> list[tuple[str, str]] | list[tuple[bytes, bytes]]: ...
